config/routes.rb
Rails.application.routes.draw do
  # root path
  root "sessions#new"

  #Users path
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  #sessions Path
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :blogs


  namespace :api do
    resources :blogs
    get '/signup' => 'users#new'
    post '/users' => 'users#create'
  
    #sessions Path
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
  end
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/api/blogs_controller.rb
class Api::BlogsController < ApplicationController
  before_action :authenticate_user
  before_action :set_blog, only: %i[show update destroy]

  # GET /api/blogs
  def index
    @blogs = Blog.all
    render json: @blogs
  end

  # GET /api/blogs/1
  def show
    render json: @blog
  end

  # POST /api/blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      render json: @blog, status: :created, location: api_blog_url(@blog)
    else
      render json: @blog.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /api/blogs/1
  def update
    if @blog.update(blog_params)
      render json: @blog
    else
      render json: @blog.errors, status: :unprocessable_entity
    end
  end

  private

  def authenticate_user
    token = request.headers['Authorization']&.split(' ')&.last
    unless token_valid?(token)
      render json: { error: 'Unauthorized. Token is missing or invalid.' }, status: :unauthorized
    end
  end

  def token_valid?(token)
    return false unless token
  
    begin
      secret_key_base = Rails.application.secrets.secret_key_base
      decoded_token = JWT.decode(token, nil, false)
      return true
    rescue JWT::DecodeError
      return false
    end
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      # Generate JWT token
      token = generate_token(user.id)

      render json: { user_id: user.id, token: token, message: 'Login successful' }
    else
      render json: { error: 'Invalid Email or Password' }, status: :unauthorized
    end
  end

  def destroy
    render json: { message: 'Logged Out' }
  end

  private

  def generate_token(user_id)
    payload = { user_id: user_id }
    secret_key = Rails.application.secret_key_base

    JWT.encode(payload, secret_key, 'HS256')
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    user = User.new(user_params)

    if user.save
      render json: { message: 'Signup successful' }, status: :created
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
def create
  user = User.find_by(email: params[:email])

  if user&.authenticate(params[:password])
    session[:user_id] = user.id
    flash[:notice] = 'Login successful'
    redirect_to blogs_path
  else
    flash[:alert] = 'Invalid Email or Password'
    render :new
  end
end


  def destroy
    session[:user_id] = nil
    flash[:notice]="Logged Out"
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end
  
  def create
    user = User.new(user_params)
    if user.save
      flash[:notice]="Signup successful"
      redirect_to blogs_path
    else
      flash[:notice]="Please try again"
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= blog.content %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div class="class = "d-inline-flex mt-3">
    <%= form.submit class: 'btn btn-success' , style: 'margin-right: 10px; margin-left:10px;'%>  |
    <%= link_to "Show this blog", @blog, class: 'btn btn-primary' , style: 'margin-right: 10px; margin-left:10px;'%> |
    <%= link_to "Back to Blogs", blogs_path, class: 'btn btn-secondary', style: 'margin-right: 10px; margin-left:10px;' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container mt-4">
  <h1>Editing Blog</h1>

  <%= render "form", blog: @blog %>

  
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-4">
  <h1 class="mb-4">Blogs</h1>

  <% if @blogs.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @blogs.each do |blog| %>
          <tr>
            <td><%= blog.title %></td>
            <td><%= blog.content %></td>
            <td class = "d-inline-flex">
            <%= link_to "Show", blog, class: 'btn btn-primary btn-sm', style: 'margin-right: 10px;' %>
            <%= link_to "Edit", edit_blog_path(blog), class: 'btn btn-warning btn-sm', style: 'margin-right: 10px;' %>
              <%= link_to "Delete", @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No blogs available.</p>
  <% end %>

  <%= link_to "New blog", new_blog_path, class: 'btn btn-success mt-4' %>

  <div style="text-align: right;">
    <% if current_user %>
      <%= link_to "Logout", logout_path, method: :delete, class: 'btn btn-secondary mt-4' %>
    <% else %>
      <%= link_to "Login", login_path, class: 'btn btn-primary mt-4' %>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container mt-4">
  <h1>New Blog</h1>

  <%= render "form", blog: @blog %>

  <div class="mt-3">
    <%= link_to "Back to Blogs", blogs_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container d-flex align-items-center justify-content-center mt-4">
  <div class="col-md-8">
    <p style="color: green"><%= notice %></p>

    <%= render @blog %>

    <div class = "d-inline-flex mt-3">
    <%= link_to "Edit this blog", edit_blog_path(@blog), class: 'btn btn-warning',  style: 'margin-right: 10px; margin-left:10px;' %>    |
    <%= link_to "Back to Blogs", blogs_path, class: 'btn btn-secondary', style: 'margin-right: 10px; margin-left:10px;' %>     |
    <%= button_to "Destroy this blog", @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', style: 'margin-right: 10px; margin-left:10px;' %>
  </div>
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<section class="h-100 h-custom" style="background-color: #8fc4b7;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-8 col-xl-6">
        <div class="card rounded-3">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp"
            class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
            alt="Sample photo">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Registration Info</h3>

            <%= form_for :user, url: "/users", class: "signupForm px-md-2" do |f| %>
              <div class="form-outline mb-4">
                <%= f.label :email, "Email Address" %>
                <%= f.text_field :email, class: "shortInput form-control" %> <br />
                
                <%= f.label :password %>
                <%= f.password_field :password, class: "shortInput form-control" %> <br />
                
                <%= f.label :password_confirmation, "Confirm Password" %>
                <%= f.password_field :password_confirmation, class: "shortInput form-control" %> <br />
              </div>
                <%= f.submit "Register", class: "button createAccount btn btn-primary" %>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>